package com.service;

import com.pojo.Books;
import com.pojo.BooksExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @param
 * @BelongsProject: SSM_CRUD
 * @BelongsPackage: com.service
 * @Date: 2022/4/17 21:53
 * @Description: TODO
 * @return
 */

public interface BooksService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    int countByExample(BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    int deleteByExample(BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    int insert(Books record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    int insertSelective(Books record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    List<Books> selectByExample(BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    int updateByExampleSelective(@Param("record") Books record, @Param("example") BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    int updateByExample(@Param("record") Books record, @Param("example") BooksExample example);
}
