package com.pojo;

public class Books {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.bookID
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    private Integer bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.bookName
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.bookCounts
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    private Integer bookcounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.detail
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.bookID
     *
     * @return the value of books.bookID
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.bookID
     *
     * @param bookid the value for books.bookID
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.bookName
     *
     * @return the value of books.bookName
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.bookName
     *
     * @param bookname the value for books.bookName
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.bookCounts
     *
     * @return the value of books.bookCounts
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    public Integer getBookcounts() {
        return bookcounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.bookCounts
     *
     * @param bookcounts the value for books.bookCounts
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    public void setBookcounts(Integer bookcounts) {
        this.bookcounts = bookcounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.detail
     *
     * @return the value of books.detail
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.detail
     *
     * @param detail the value for books.detail
     *
     * @mbggenerated Sun Apr 17 21:40:04 CST 2022
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    @Override
    public String toString() {
        return "Books{" +
                "bookid=" + bookid +
                ", bookname='" + bookname + '\'' +
                ", bookcounts=" + bookcounts +
                ", detail='" + detail + '\'' +
                '}';
    }

    public Books() {
    }

    public Books(Integer bookid, String bookname, Integer bookcounts, String detail) {
        this.bookid = bookid;
        this.bookname = bookname;
        this.bookcounts = bookcounts;
        this.detail = detail;
    }
}